### ISSUE TITLE
Host Cannot Call Plugin

### ISSUE THREAD

**Issue by anxuanzi** [knqyf263/go-plugin#11]
I have five methods defined in the `.proto` file, and only one of them works when calling them in the host. I tried to find out what happened, but it seems like after calling from the host, the default result struct is returned without value.

here are the proto files and generated codes: https://github.com/wshops/wshop-plugin-common

host code
```go
func TestPluginFunction(t *testing.T) {
	ctx := context.Background()
	p, err := pcaptcha.NewCaptchaPlugin(ctx, pcaptcha.CaptchaPluginOption{
		Stdout: os.Stdout,
		Stderr: os.Stderr,
	})
	if err != nil {
		t.Error(err)
	}

	pluginInstance, err := p.Load(ctx, "./plugins/captcha/hcaptcha.wasm")
	if err != nil {
		t.Error(err)
	}

	pi, err := pluginInstance.GetPluginInfo(ctx, emptypb.Empty{})
	if err != nil {
		t.Error(err)
	}
	fmt.Println("plugin version: ", pi.GetVersion())

	res, err := pluginInstance.VerifyCaptcha(ctx, pcaptcha.VerifyCaptchaRequest{Captcha: "123"})
	if err != nil {
		t.Error(err)
	}
	fmt.Println("verify result: ", res.GetIsValid())

	htmlInput, err := pluginInstance.GetCustomHtmlInputField(ctx, emptypb.Empty{})
	if err != nil {
		t.Error(err)
	}
	fmt.Println("input html: ", htmlInput.GetHtml())

	htmlHead, err := pluginInstance.GetCustomHtmlHead(ctx, emptypb.Empty{})
	if err != nil {
		t.Error(err)
	}
	fmt.Println("head html: ", htmlHead.GetHtml())

	htmlBody, err := pluginInstance.GetCustomHtmlBodyEnd(ctx, emptypb.Empty{})
	if err != nil {
		t.Error(err)
	}
	fmt.Println("body html: ", htmlBody.GetHtml())

	t.Cleanup(func() {
		p.Close(ctx)
	})
}
```
---

result:
```
=== RUN   TestPluginFunction
plugin version:  
validating captcha...
verify result:  true
input html:  
head html:  
body html:  
```

---
version
go: `go1.19.2`
go-plugin: `v0.3.0`
sys: `MacOS 13.0.1`
chip: `Apple M1 Max`

**Comment by mathetake** [comment]
hey @anxuanzi could you upload the plugin's source code as well or better still check-in the `./plugins/captcha/hcaptcha.wasm` directly in the repo together with the failing test case?  That way we can reproduce the bug locally and that would make it easy for us to dig

**Comment by mathetake** [comment]
and maybe you want to try the latest go-plugin as I can see you are using `v0.1.0` https://github.com/wshops/wshop-plugin-common/blob/main/pkg/wpc/common.pb.go#L3

**Comment by anxuanzi** [comment]
Hey @mathetake, I'm pretty sure I downloaded the latest binary from the release on GitHub of go-plugin (I just did it again). After generating the code, the version number doesn't change, still saying 0.1.0.

**Comment by anxuanzi** [comment]
I just updated the repository with the example code and wasm file.

**Comment by mathetake** [comment]
https://github.com/knqyf263/go-plugin/pull/12 here's a fix! thanks for reporting!

**Comment by knqyf263** [comment]
Thank you guys 👍

**Comment by codefromthecrypt** [comment]
@anxuanzi released! https://github.com/knqyf263/go-plugin/releases/tag/v0.4.0
