### ISSUE TITLE
too many arguments in call to p.module.Memory().Size

### ISSUE THREAD

**Issue by amlwwalker** [knqyf263/go-plugin#19]
Hi,
I am trying to get the helloworld example working with the evening greeter. My app structure is currently

```shell
.
├── build
├── main.go
└── plugins
    ├── greeter
    │   └── protos
    └── plugin-evening
```
My final app ends up in `build`, `main.go is loading the plugin, `plugins` holds all my plugins and the greeter interface, the proto file and the generated pb.go files. `plugin-evening` is the example plugin.

I set `option go_package = "plugins/greeter/protos";` in the protos file so that the path is the same as where the protos are and the generated go files. I have updated this path in the `plugin-evening.go` file - however (limited knowledge here) my IDE recommended I set the import to `greeting "changeme/plugins/greeter/protos"` - I'm not sure why the `changeme`

I have set the same import in my main.go `greeting "changeme/plugins/greeter/protos"`

I'm then calling 

```go
	ctx := context.Background()
	p, err := greeting.NewGreeterPlugin(ctx, greeting.GreeterPluginOption{})
	if err != nil {
		return err
	}
	defer p.Close(ctx)
	eveningPlugin, err := p.Load(ctx, "plugins/plugin-evening/evening.wasm")
	if err != nil {
		return err
	}
	reply, err := eveningPlugin.Greet(ctx, greeting.GreetRequest{
		Name: "go-plugin",
	})
	if err != nil {
		return err
	}

	fmt.Println(reply.GetMessage())
```

I'm getting an error:

```
  ERROR
          # changeme/plugins/greeter/protos
          plugins/greeter/protos/greet_host.pb.go:154:53: too many arguments in call to p.module.Memory().Write
          	have (context.Context, uint32, []byte)
          	want (uint32, []byte)
          plugins/greeter/protos/greet_host.pb.go:155:129: too many arguments in call to p.module.Memory().Size
          	have (context.Context)
          	want ()
          plugins/greeter/protos/greet_host.pb.go:169:51: too many arguments in call to p.module.Memory().Read
          	have (context.Context, uint32, uint32)
          	want (uint32, uint32)
          plugins/greeter/protos/greet_host.pb.go:172:44: too many arguments in call to p.module.Memory().Size
          	have (context.Context)
          	want ()

          exit status 2
```

any idea as to why that would happen?

**Comment by codefromthecrypt** [comment]
seems like you are using a newer version of wazero. I just cut v0.5.0 which includes it. maybe try again!

**Comment by amlwwalker** [comment]
EDIT: I suspect this might have to do with me trying to use this library, so my sample looks like

```
.
├── go.mod
├── go.sum
├── main.go
├── pb
│   └── greeting
│       ├── greeting.pb.go
│       ├── greeting_host.pb.go
│       ├── greeting_plugin.pb.go
│       └── greeting_vtproto.pb.go
├── plugins
│   └── host
│       ├── host.go
│       └── host.wasm
└── proto
    └── greeting.proto
```

I generated the greenting files from the proto file with

```
protoc --go-plugin_out=./pb --go-plugin_opt=paths=source_relative --proto_path=./proto ./proto/greeting.proto
```
Then I have compiled the plugin with 

```
tinygo build -o plugins/host/host.wasm -scheduler=none -target=wasi --no-debug plugins/host/host.go
```

I seemed to have no choice but to import the greeting package absolutely, however I would like advice on how to do it relatively

```
import (greeting "github.com/username/go-grpc-plugins/pb/greeting")
```

Then in main I'm importing

```
import (
	"context"
	"fmt"
	"github.com/username/go-grpc-plugins/pb/greeting"
	"github.com/knqyf263/go-plugin/types/known/emptypb"
	"io"
	"log"
	"net/http"
)
```

and as before I get the errors

```
# github.com/knqyf263/go-plugin/wasm
../../knqyf263/go-plugin/wasm/host.go:16:42: too many arguments in call to m.Memory().Read
	have (context.Context, uint32, uint32)
	want (uint32, uint32)
../../knqyf263/go-plugin/wasm/host.go:41:45: too many arguments in call to m.Memory().Write
	have (context.Context, uint32, []byte)
	want (uint32, []byte)
../../knqyf263/go-plugin/wasm/host.go:43:40: too many arguments in call to m.Memory().Size
	have (context.Context)
	want ()
```

I tried to do a `replace in the `go.mod` like

```
replace github.com/knqyf263/go-plugin => /Users/username/go/src/github.com/knqyf263/go-plugin
```

however that hasn't helped.

Any ideas? Thank you!

**Comment by amlwwalker** [comment]
hey @codefromthecrypt and @knqyf263 thanks for responding - 0.5 has fixed everything and re-established my faith in my understanding!
