### ISSUE TITLE
Similar approach called Karmem.

### ISSUE THREAD

**Issue by gedw99** [knqyf263/go-plugin#2]
https://github.com/inkeliz/karmem

Supports many languages and fast .

not say protocol buffers are not nice, but just wanted to let you know about another approach.

there is no tie into Wazero in that repo.

**Comment by knqyf263** [comment]
Yes, I know karmem. I wanted to use the same schema as Protocol Buffers as it is used in hashicorp/go-plugin and famous. Also, protobuf has well-known types that support `interface` and timestamp. It is more flexible even though it has some performance penalties.

**Comment by gedw99** [comment]
Yep totally get you. Everyone know Protobufs :) 

perf is def not everything

**Comment by gedw99** [comment]
Will close this if you don’t mind . Feel free to reopen
