### ISSUE TITLE
Plugin seems to be closing. Saving plugins in a map and calling on functionality elsewhere

### ISSUE THREAD

**Issue by amlwwalker** [knqyf263/go-plugin#20]
Hey, I might have missed something. I am loading plugins like so

```go
        pluginMap := make(map[string]*MyPlugin)
	filepath.Walk(root, func(path string, info os.FileInfo, err error) error  {

		if !info.IsDir() && filepath.Ext(path) == EXT {
			if this, err := p.Load(ctx, path, PluginFunctions{}); err != nil {
				return err
			} else {
				pluginMap[uuid.New().String()] = &this
			}
		}
		return nil
	})
	m.plugins = pluginMap
```

then from "somewhere else" I am calling 

```go
func (p PluginManager) CallContentOnPlugins(ctx context.Context) error {
	for _, v := range p.plugins {
		content, err := (*v).Content(ctx, emptypb.Empty{})
		if err != nil {
			return err
		}
		fmt.Println("render content ", content.GetContent())
	}
	return nil
}
```

If I were to do this directly, in the first code snippet above where I am adding the plugin to the map, it works fine. However when I try to do this from this function, I get the error 

```shell
error module "" closed with exit_code(0)
```

My guess is that I would have to keep calling `.Load` on the plugin however I would have thought all would be OK as I am storing the plugin in the map as a reference, but for some reason that doesnt' work? Any tips as to why?

(on another note, is there ways to expose functions in the plugin to the 'host' at runtime - i.e functions that are not known about in the proto file. Perhaps with reflection, or perhaps with a map of functions in the plugin that are exposed in the proto file?)

Thanks for your help!

**Comment by amlwwalker** [comment]
EDIT - it seems that passing a plugin around is causing the crash... is that something that makes any sense?

**Comment by amlwwalker** [comment]
I got it!

The issue was the plugin loader was `defer p.Close(ctx)` closing. I had not thought that this needed to be open for a plugin to work, but it makes sense now. I'll add that to my struct and close it later. 

Hopefully this helps someone

**Comment by codefromthecrypt** [comment]
Thanks for putting the comment back about what happens. It helps to share this info, @amlwwalker, even if only to re-enforce the point.
