### ISSUE TITLE
Is using values instead of pointers is by design?

### ISSUE THREAD

**Issue by inliquid** [knqyf263/go-plugin#29]
I noticed that `gen-go-pugin` generates code which uses values, so the code looks like:
```go
// The greeting service definition.
// go:plugin type=plugin version=1
type Greeter interface {
	SayHello(context.Context, GreetReq) (GreetResp, error)
}
```

While gRPC plugin generates this code from the same `*.proto` definition:
```go
// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *GreetReq, opts ...grpc.CallOption) (*GreetResp, error)
}
```

This also makes `gopls` complain about copying of `sync.Mutex`:
![изображение](https://user-images.githubusercontent.com/6797881/221593793-8c9a16eb-3db6-4a1e-9156-6273d0e7a80b.png)

If it's by design, I would like to learn more about it.

**Comment by codefromthecrypt** [comment]
personally, I doubt this is by design and unless someone screams you can raise a PR to change it, worst case we can revert if get a late scream. This is a detail important to finalize before any 1.0

**Comment by knqyf263** [comment]
Looks like we should change it to pointers.
