### ISSUE TITLE
protoc-gen-go-plugin always generate it's hardcoded version

### ISSUE THREAD

**Issue by dmvolod** [knqyf263/go-plugin#37]
A new latest release (v0.6.0) was downloading, but after generating files from scratch, the first hard-coded `protoc-gen-go-plugin v0.1.0` version was added.

```
// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.12
```

**Comment by dmvolod** [comment]
If `ldflags` redefining values not from main package, import path shouldn't be omitted.

**Comment by codefromthecrypt** [comment]
thanks for noticing and the fast turnaround. fixing things before someone else notices is excellent OSS stewardship!
