### ISSUE TITLE
Allow using together with `protoc-gen-go`

### ISSUE THREAD

**Issue by saschagrunert** [knqyf263/go-plugin#67]
Hey, right now using both `protoc-gen-go` and `protoc-gen-go-plugin` together will result in:

```
> protoc --go-plugin_out=. --go-plugin_opt=paths=source_relative --go_out=. --go_opt=paths=source_relative pkg/api/api.proto
pkg/api/api.pb.go: Tried to write the same file twice.
```

Would it be possible to run both plugins together so that they can share the types?

Somehow related to https://github.com/cri-o/cri-o/pull/8715, https://github.com/containerd/nri/issues/120

**Comment by knqyf263** [comment]
As [written in README](https://github.com/knqyf263/go-plugin?tab=readme-ov-file#why-not-using-protobuf-go-directly), TinyGo doesn't work with the code generated by `protoc-gen-go`. `go-plugin` ported the code from github.com/protocolbuffers/protobuf-go and added some modifications so that it can work with TinyGo.

**Comment by knqyf263** [comment]
However, that was two years ago. The situation might have changed now. https://github.com/tinygo-org/tinygo/issues/2667
If you confirm the latest TinyGo works with `protoc-gen-go`, we can remove the ported code and let `protoc-gen-go` generate `xxx.pb.go`.

**Comment by saschagrunert** [comment]
> If you confirm the latest TinyGo works with `protoc-gen-go`

Did a test using:

```
tinygo version 0.34.0 linux/amd64 (using go version go1.23.2 and LLVM version 18.1.8)
```
And: https://github.com/containerd/nri/blob/main/pkg/api/api.proto

```bash
mkdir tmp && protoc --go_out=tmp --go_opt=paths=source_relative ./pkg/api/api.proto
```

Then using a `main.go` like:
```go
package main

import (
	"github.com/containerd/nri/tmp/pkg/api"
)

func main() {
	_ = &api.RegisterPluginRequest{}
}
```

Which builds successfully using tinygo:
```bash
tinygo build -scheduler=none -target=wasi -no-debug main.go
```

**Comment by knqyf263** [comment]
If I remember correctly, some errors occur at runtime. Did you successfully run the code?

**Comment by inliquid** [comment]
I'am still getting errors when compiling using more or less complex proto definitions:
```
$ tinygo build -o wasm/plugin.wasm -scheduler=none -target=wasip1 --no-debug ./wasm
../../../../pkg/mod/golang.org/x/net@v0.30.0/http2/transport.go:26:2: package net/http/httptrace is not in std (/home/***/.cache/tinygo/goroot-8cbcb1d9555609a60075264735fce03217a624835ebf583eb96aa0c5bf08e840/src/net/http/httptrace)
../../../../pkg/mod/google.golang.org/grpc@v1.66.0-dev/internal/transport/proxy.go:29:2: package net/http/httputil is not in std (/home/***/.cache/tinygo/goroot-8cbcb1d9555609a60075264735fce03217a624835ebf583eb96aa0c5bf08e840/src/net/http/httputil)
```

Tracking issues: https://github.com/tinygo-org/tinygo/issues/2704 and https://github.com/tinygo-org/tinygo/issues/4580

**Comment by saschagrunert** [comment]
@inliquid this is probably because of the gRPC generated code

**Comment by inliquid** [comment]
> this is probably because of the gRPC generated code

Most likely it is. The package referred to by the wasm module is quite complex, I would like to just import it, but can't, so have to re-generate these definitions locally as well using `go-plugin`.

**Comment by saschagrunert** [comment]
> If I remember correctly, some errors occur at runtime. Did you successfully run the code?

Yes, the binary runs using wasmedge, but the tests may not provide enough data.
