### ISSUE TITLE
wasm error running example 

### ISSUE THREAD

**Issue by goliatone** [knqyf263/go-plugin#7]
Running the host-functions example I get the following error:

```
2022/11/12 14:42:05 Sending a HTTP request...
2022/11/12 14:42:05 wasm error: unreachable
wasm stack trace:
	.runtime.runtimePanic(i32,i32)
	.runtime.lookupPanic()
	.malloc(i32) i32 (recovered by wazero)
wasm stack trace:
	env.log(i32,i32) i64
	.greeter_greet(i32,i32) i64
```

* go version go1.18.7 darwin/arm64
* macOS 12.6.1 
* Chip M1 Max

**Comment by knqyf263** [comment]
Which version did you try?

**Comment by anxuanzi** [comment]
Hey, I have the same problem with loading my plugin

- MacOS: `13.0.1`
- Chip: `Apple M1 Max`
- Go: `go1.19.2 darwin/arm64`
- go-plugin: `0.2.0`

```
[2022/11/17T19:29:43] [application] [ERROR] [core.go:82,func1] wasm error: unreachable
wasm stack trace:
	.runtime.runtimePanic(i32,i32)
	.runtime.lookupPanic()
	.malloc(i32) i32  
```

**Comment by knqyf263** [comment]
@codefromthecrypt Is it relevant to the recent update of wazero?

**Comment by mathetake** [comment]
it seems something to do with the memory management change in TinyGo, but haven't looked into yet

**Comment by mathetake** [comment]
maybe adds the test dimension with TinyGo versions since i see go-plugin is only tested with TinyGo 0.24 which is two versions behind the latest

**Comment by knqyf263** [comment]
@mathetake Thanks for your insight.
@goliatone Which version of TinyGo are you using?

**Comment by goliatone** [comment]
@knqyf263 `tinygo version 0.26.0 darwin/amd64 (using go version go1.18.7 and LLVM version 14.0.0)`

**Comment by mathetake** [comment]
I imagine this commit is the root cause https://github.com/tinygo-org/tinygo/pull/3245. since that commit (included in 0.26), passing size=0 to the malloc results in panic.

**Comment by mathetake** [comment]
cc @anuraaga

**Comment by mathetake** [comment]
https://github.com/knqyf263/go-plugin/pull/9 fixes!

**Comment by knqyf263** [comment]
@goliatone Do you mind trying the latest commit?

**Comment by codefromthecrypt** [comment]
I verified tinygo 0.26 works via https://github.com/knqyf263/go-plugin/pull/10 also

**Comment by anuraaga** [comment]
Thanks for the pointer, sent https://github.com/tinygo-org/tinygo/pull/3303 to fix in TinyGo
