### ISSUE TITLE
Error when loading plugin

### ISSUE THREAD

**Issue by anxuanzi** [knqyf263/go-plugin#8]
Hey, I got the following errors when loading my plugin.

```
wasm error: unreachable
wasm stack trace:
	.runtime.runtimePanic(i32,i32)
	.runtime.lookupPanic()
	.malloc(i32) i32
```

- MacOS: `13.0.1`
- Chip: `Apple M1 Max`
- Go: `go1.19.2 darwin/arm64`
- go-plugin: `0.2.0`

**Comment by mathetake** [comment]
could you close this as this is clearly the dup of #7?

**Comment by codefromthecrypt** [comment]
notes here https://github.com/knqyf263/go-plugin/releases/tag/v0.3.0
